services:
  - type: worker
    name: trendsniper-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
